import React from 'react'
import {Metadata} from 'next'
import {Providers} from '@/components/providers/Providers'
import Layout from "@/components/layout/Layout";

import './globals.css'
import Head from "next/head";
import styles from "@/app/styles/Layout.module.scss";
import {TheHeader} from "@/components/theHeader/TheHeader";

export const metadata: Metadata = {
	title: 'Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
																		 children
																	 }: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>

		<Head>
			<meta charSet="UTF-8"/>
			<meta httpEquiv="x-ua-compatible" content="ie=edge"/>
			<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
			<meta name="format-detection" content="telephone=no, date=no, email=no, address=no"/>
		</Head>

		<Providers>
		<body>
		<div className={styles.header}>
			<TheHeader/>
		</div>
		<Layout isFooterHidden>{children}</Layout>
		</body>
		</Providers>
		</html>
	)
}
