import { Providers } from '@/components/providers/Providers';
import Header from '@/components/header/Header';
import Footer from '@/components/footer/Footer';
import type { Metadata } from 'next';
import './globals.css';


export const metadata:Metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
};

export default function RootLayout(
  { children }:Readonly<{
        children:React.ReactNode;
    }>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header/>
          <main className='container'>{ children }</main>
          <Footer/>
        </Providers>
      </body>
    </html>
  );
}
